---
title: "wk06_widgets_grop"
author: "fish-ecol team"
date: "13 de febrero de 2016"
output:
  html_document:
    fig_caption: yes
    toc: yes
---

# Authorship

- Juan and Niko compiled all data
- Juan Carlos and Patricia did the Vis's

```{r, "wordcloud", echo=FALSE}

library("d3wordcloud")# devtools::install_github("jbkunst/d3wordcloud")

words <- c("IUCN", "Redlist", "fish-ecol", "Endangered", "Species")

freqs <- sample(seq(length(words)))

d3wordcloud(words, freqs)
```

# Taxonomic composition of our data

```{r, "TaxTree", echo=FALSE}
# You wil have to install some packages:
suppressPackageStartupMessages({
  library(readr)
  library(dplyr)
  library(tidyr)
  library(treemap)
  library(data.tree)
  library(DT)
  library(ape)
  library(networkD3)
  library(ggplot2)
  library(knitr)
  library(googleVis)
  library(devtools)
  load_all("./fish.ecol")
})

```

```{r, include=FALSE, eval=FALSE}
#Change options above to recalculate. WARNING IT TAKES A LOT OF TIME

#We read the Taxonomic data from csv file, and select columns of interest. The first attempt created a horrible phylo tree. I decided to create another with only CR, EN, and VU species. Both files are stored as *.RData, just in case.
taxdata=read_csv("./data/Taxonomic_and_Status.csv") %>%
  filter(Category==c("CR", "EN"),Class=="CHONDRICHTHYES") %>%
  select(Class, Order, Family, Genus, `Scientific Name`, Category)

#taxdata.csv created to be used by the Shiny-fish-ecol 
write.csv(taxdata, file = "Shiny-fish-ecol/data/taxdata.csv")

# # We need no create a "pathString". This is a single string that contains all taxonomic information for each species. Therefore, pathString is a column like "SARCOPTERYGII/COELACANTHIFORMES/LATIMERIIDAE/Latimeria/Latimeria chalumnae". This string is used later in as.Node as to indicate the function how to build the tree.
#
taxdata$pathString=paste(taxdata$Class,
                         taxdata$Order,
                         taxdata$Family,
                         taxdata$Genus,
                         taxdata$`Scientific Name`,
                         sep="/")
#
# #We can now build the tree, by indicating the data, type of data, delimiter, and path
taxtree=as.Node(taxdata, mode="table", pathDelimiter="/", pathName="pathString")
#
taxlist=ToListExplicit(taxtree, unname = TRUE) #We can convert this to a list, and feed it to a Network graph
#
# We must save the files taxtree(Node) and taxtlist(List), because creating the tree takes A LOT. We can later just load them with load("filename.extension")
# save(taxtree, file="Data/taxtreeCR.RData")
# save(taxlist, file="Data/taxListCR.RData")
```

## Table

Our taxonomical tree looks like this. This is only for the first two species, in a total of... a lot.

```{r, "load", echo=FALSE}
#load("taxList.RData") #Uncomment to use all species (loads data)
#load("taxttree.RData") #Uncomment to use all species (loads data)

load("Data/taxListCR.RData")
load("Data/taxtreeCR.RData")

print(taxtree, limit=10)

```


## Tree

Taxonomic tree of species under IUCN's **CR** category. *Hover* over a node to see the text grow.
```{r, "phylotree", echo=FALSE, fig.width=9, fig.height=9}
#radialNetwork(taxlist) #Uncomment to use all species (plots)
radialNetwork(taxlist, fontSize=20, nodeColour="blue", textColour="black", opacity=1, linkColour="black")
```

# World map IUCN index


```{r, Maping IUCN Category Index per Country, results='asis',tidy=FALSE, echo=FALSE}
#by: Patricia
#run this chunk to get the Geo chart

fishData <- read_csv(file="Data/Long Format Collected Fish Information IUCN")     #read cvs always with _ (as: read_csv) it keep the data without factors

#fishData$index <- NA
# unique(fishData$Category) #Shows all the categories only one time
# "LC"    "VU"    "NT"    "CR"    "EN"    "DD"    "LR/nt"

#Critically endangered (CR) – Extremely high risk of extinction in the wild.
#Endangered (EN) – High risk of extinction in the wild.
#Vulnerable (VU) – High risk of endangerment in the wild.
#Near threatened (NT) – Likely to become endangered in the near future.
#LR/nt = Lower Risk/near threatened (I didn't find a definition for this category)
#Least concern (LC) – Lowest risk. Does not qualify for a more at-risk category. Widespread and abundant taxa are included in this category.
#Data deficient (DD) – Not enough data to make an assessment of its risk of extinction.

#fishData$Category <- as.character(fishData$Category) #Tranform from Factor to Characters

#proposal number for each category, PLEASE REVIEW!
cat2val = read_csv(
'Category,index
DD,1
LC,2
LR/nt,3
NT,4
VU,5
EN,6
CR,7')

#This is the file with the ISO3 and Country name
conversion <- read_csv(file="Data/CountryConversion.csv")


fishDataCountries = fishData %>%           #generating the fishDataCountries output
  left_join(                               #joining fishData with cat2val
    cat2val, 
    by = c("Category")) %>%         
  rename(ISO3=CountryISO3) %>%             #rename common column with ISO3
  left_join(                               #joining fishData with conversion by ISO3
    conversion, 
    by = c("ISO3")) 


fishData2 = fishDataCountries %>%                     
  group_by(World_Bank_Country,ISO2) %>%             #grouping by ISO2 column
  summarize(score = iucn_index(Category, type="b"), mean=mean(index)) #Calculates a score based on our new iucn_index function

# Plot countries, I am using the mean as an example of the index that we want to show in this map (we have to create the index) 

fishData2$levels <- levels(fishData2$score)  #Creating display leyend levels for each country in the map


op <- options(gvis.plot.tag='chart')
#### Create a geo chart

colnames(fishData2)=c("Country", "ISO2", "score")
G1 <- gvisGeoChart(fishData2, "ISO2", "score", hovervar="Country",
                   options=list(gvis.editor="S&P",
                             colorAxis="{colors:['#91BFDB', '#FC8D59']}"))
plot(G1)
```
